# Generated by Django 6.0.4 on 2026-05-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dodavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Inventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_zahajenia', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.CharField(max_length=100)),
                ('vykonal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NavrhObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.CharField(choices=[('NS', 'Na schválenie'), ('OD', 'Odoslané'), ('ZA', 'Zamietnuté')], default='NS', max_length=2)),
                ('datum_vytvorenia', models.DateTimeField(auto_now_add=True)),
                ('dodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dodavatel')),
            ],
        ),
        migrations.CreateModel(
            name='ProtokolInventury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zisteny_rozdiel', models.IntegerField()),
                ('poznamka', models.TextField(blank=True)),
                ('inventura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.inventura')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=255)),
                ('ean_kod', models.CharField(max_length=13, unique=True)),
                ('kriticky_limit', models.IntegerField(default=10)),
                ('dodavatel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dodavatel')),
            ],
        ),
        migrations.CreateModel(
            name='Sarza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sarze', models.CharField(max_length=100)),
                ('mnozstvo', models.IntegerField()),
                ('datum_exspiracie', models.DateField()),
                ('aktualna_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarze', to='api.tovar')),
            ],
        ),
        migrations.CreateModel(
            name='PolozkaNavrhu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvo', models.IntegerField()),
                ('cena_pri_objednavke', models.DecimalField(decimal_places=2, max_digits=10)),
                ('navrh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='api.navrhobjednavky')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tovar')),
            ],
        ),
    ]
